services:
  - type: web
    name: by-pro-accounts-login
    env: node
    plan: free
    rootDir: src
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
