services:
  - type: web
    name: secure-auth-app
    runtime: node
    nodeVersion: "22.x"  # استخدام أحدث إصدار LTS من Node.js
    buildCommand: |
      cd backend && \
      npm install && \
      npm run build
    startCommand: npm start
    env: node
    envVars:
      # MongoDB Atlas Configuration
      - key: MONGODB_URI
        value: mongodb+srv://yacine:ABC123%21%3F%2F@cluster0.wyjnom4.mongodb.net/auth-system?retryWrites=true&w=majority
      
      # JWT Configuration
      - key: JWT_SECRET
        value: your_strong_secret_key_here_123!@#ABC
      - key: JWT_EXPIRES_IN
        value: 1h
      
      # Email Configuration (Gmail)
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        value: byprosprt2007@gmail.com
      - key: EMAIL_PASS
        value: envgpuaigrssllbg
      - key: EMAIL_FROM
        value: Secure Auth System <byprosprt2007@gmail.com>
      
      # Application Configuration
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://yacine2007.github.io  # تعديل هذا حسب عنوان GitHub Pages الخاص بك
      - key: BACKEND_URL
        value: https://secure-auth-app-5w01.onrender.com  # تعديل هذا حسب عنوان Render الخاص بك
      
      # Rate Limiting
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000  # 15 دقيقة (15*60*1000)
      - key: RATE_LIMIT_MAX
        value: 100
      
      # Verification Code
      - key: VERIFICATION_CODE_EXPIRY_MINUTES
        value: 10
      - key: VERIFICATION_CODE_RESEND_DELAY_SECONDS
        value: 30
