services:
  - type: web
    name: by-pro-accounts-login
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
